export const ROUTES = {
  home: '/',
  play: '/play',
  train: '/train',
  patterns: '/patterns',
  endgames: '/endgames',
  openings: '/openings',
  games: '/games',
  notes: '/notes',
  study: '/study',
  commandCenter: '/hub',
  dashboard: '/dashboard',
  skills: '/skills',
  achievements: '/achievements',
  mistakes: '/mistakes',
  settings: '/settings',
  calmPlay: '/calm-play',
  mind: '/mind',
  journey: '/journey',
  beginner: '/beginner',
  greats: '/greats',
  courses: '/courses',
  social: '/social',
  studyPlan: '/study-plan',
  coach: '/coach',
  tournament: '/tournament',
  flashTraining: '/flash-training',
  thinkingSystem: '/thinking-system',
  dailyChallenges: '/daily-challenges',
  spacedRepetition: '/spaced-repetition',
  blindfold: '/blindfold',
  intuition: '/intuition',
  weaknessDetector: '/weakness-detector',
  pricing: '/pricing',
  auth: '/auth',
  authCallback: '/auth/callback',
  aiCoach: '/ai-coach',
  playFriend: '/play/friend',
  howTo: '/how-to',
  privacy: '/privacy',
  terms: '/terms',
} as const;

export type AppRoute = (typeof ROUTES)[keyof typeof ROUTES];
